# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [21]:
import numpy as np
print(np.__version__)


1.26.4


2) Создать нулевой вектор размера 10

In [ ]:
zero = np.zeros(10)
print(zero)

Нулевой вектор размера 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [2]:
seven = np.full(7, 7)
print(seven)

 вектор заполненный 7-ами размера 7 [7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [20]:
vector = np.arange(10, 101, 2)
print(vector)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [54]:
random_array = np.random.randint(1, 11, size=10)
reversed_array = random_array[::-1]
print(random_array)
print(reversed_array)


[ 4  3  8  8  7  5 10  5  5  2]
[ 2  5  5 10  5  7  8  8  3  4]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

Матрица 3x3, заполненная числами от 0 до 9:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [4]:
matrix = np.eye(4, k=1)
print(matrix)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, [1, 2, 3, 4])
print(matrix)


Матрица с числами от 1 до 4 по диагонали, остальное заполнено семерками:
[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную числами от 0 до 4 в строках.

In [ ]:
matrix_5x5 = np.tile(np.arange(5), (5, 1))
print(matrix_5x5)

Матрица 5x5, заполненная числами от 0 до 4 по строкам:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [18]:
matrix = np.random.randint(1, 11, size=(10, 10))
matrix = matrix - np.mean(matrix, axis=1, keepdims=True)
print(matrix)


[[ 2.2 -1.8 -3.8  2.2 -0.8  1.2  0.2 -1.8 -1.8  4.2]
 [ 0.2  0.2  3.2 -3.8 -3.8  5.2 -0.8  3.2 -0.8 -2.8]
 [ 3.1 -3.9 -3.9  2.1  3.1 -1.9  5.1 -0.9 -3.9  1.1]
 [ 3.6 -0.4  1.6 -2.4  1.6 -0.4 -5.4  3.6  2.6 -4.4]
 [ 3.2 -2.8 -3.8  4.2  1.2 -2.8 -1.8  3.2  4.2 -4.8]
 [-3.9  5.1 -2.9  3.1 -2.9 -2.9  3.1  0.1  3.1 -1.9]
 [-4.2 -4.2 -3.2  4.8  1.8  2.8  1.8  0.8  0.8 -1.2]
 [ 2.4 -3.6  2.4  0.4 -2.6 -0.6  0.4 -4.6  3.4  2.4]
 [-4.6  0.4  3.4 -0.6  4.4 -3.6 -1.6  2.4 -3.6  3.4]
 [ 0.5  3.5 -4.5  2.5 -2.5  0.5 -0.5  2.5  2.5 -4.5]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [22]:
matrix= np.random.randint(1, 11, size=(10, 10))
matrix_avg = matrix - np.median(matrix, axis=0, keepdims=True)
print(matrix_avg)

[[-0.5 -4.5 -1.5 -2.5  3.5  2.  -3.  -3.5 -5.   1. ]
 [ 2.5 -0.5 -0.5 -3.5 -0.5 -4.   3.  -1.5  1.   0. ]
 [-5.5 -0.5  2.5 -1.5 -1.5  0.  -2.   1.5  3.   0. ]
 [ 2.5  0.5  5.5  2.5 -1.5 -3.   0.  -1.5 -4.  -2. ]
 [ 0.5  3.5  1.5  1.5  4.5  4.   3.   2.5  0.  -1. ]
 [ 1.5 -0.5  0.5  5.5  0.5 -4.   0.   1.5  0.   3. ]
 [-6.5  3.5 -3.5 -3.5  7.5  2.  -1.  -1.5  0.   0. ]
 [ 0.5  2.5 -2.5 -2.5 -0.5 -2.   1.   3.5  2.  -4. ]
 [-1.5 -0.5 -2.5  5.5  3.5  0.  -1.  -4.5 -4.  -4. ]
 [-5.5  0.5  0.5  1.5 -0.5  1.   2.   3.5  2.   2. ]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
matrix_random_5x5 = np.random.randint(1, 11, size=(5, 5))
max_columns = matrix_random_5x5.max(axis=1).reshape(-1, 1)
min_columns = matrix_random_5x5.min(axis=1).reshape(-1, 1)
matrix_minmax = np.hstack((matrix_random_5x5, max_columns, min_columns))
print(matrix_minmax)

Матрица 5x5 (числа от 1 до 10) с добавленными столбцами максимумов и минимумов по строкам:
[[ 8  4  2  1  2  8  1]
 [ 5 10  1  8  7 10  1]
 [10  2  4  3  3 10  2]
 [ 4  7  4  3  7  7  3]
 [ 2 10 10  6  5 10  2]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [43]:

vector = np.arange(0, 52)

nechet_vector = vector[vector % 2 != 0].reshape(13, 2)
chet_vector = vector[vector % 2 == 0].reshape(2, 13)

matrix_product = np.dot(nechet_vector, chet_vector)
print(matrix_product)

inverse_matrix = np.linalg.inv(matrix_product)


[[  78   86   94  102  110  118  126  134  142  150  158  166  174]
 [ 182  206  230  254  278  302  326  350  374  398  422  446  470]
 [ 286  326  366  406  446  486  526  566  606  646  686  726  766]
 [ 390  446  502  558  614  670  726  782  838  894  950 1006 1062]
 [ 494  566  638  710  782  854  926  998 1070 1142 1214 1286 1358]
 [ 598  686  774  862  950 1038 1126 1214 1302 1390 1478 1566 1654]
 [ 702  806  910 1014 1118 1222 1326 1430 1534 1638 1742 1846 1950]
 [ 806  926 1046 1166 1286 1406 1526 1646 1766 1886 2006 2126 2246]
 [ 910 1046 1182 1318 1454 1590 1726 1862 1998 2134 2270 2406 2542]
 [1014 1166 1318 1470 1622 1774 1926 2078 2230 2382 2534 2686 2838]
 [1118 1286 1454 1622 1790 1958 2126 2294 2462 2630 2798 2966 3134]
 [1222 1406 1590 1774 1958 2142 2326 2510 2694 2878 3062 3246 3430]
 [1326 1526 1726 1926 2126 2326 2526 2726 2926 3126 3326 3526 3726]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [60]:
matrix = np.full((8,8),0)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
